# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: product-catalog-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: productCatalog
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin