# Use root/example as user/password credentials
version: '3.1'

services:

  product-catalog-db:
    container_name: product-catalog-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: productCatalog
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/docker-entrypoint-initdb.d


#  product-catalog:
#    container_name: repo-product-catalog
#    image: mtopp/buy-anywhere-product-catalog:latest
##    image: product-catalog-image
#    ports:
#      - 8081:8081
#    links:
#      - "product-catalog-db"